// Socket 데이터
const SOCKET_DATA = [
  {"group":"","SN":"1","TESTER":"3380D","PKG_TYPE":"64_LQFP","Body_Size":"10x10","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"김희국","socket_no":"64P-0.5OS-SAR1","pogo_pin":"028S-038AMR-FA","comment":""},
  {"group":"","SN":"2","TESTER":"3380D","PKG_TYPE":"48_LQFP","Body_Size":"7x7-0.5","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"김희국","socket_no":"48QP-0.50S-SAR1","pogo_pin":"028S-038AMR-FA","comment":""},
  {"group":"","SN":"3","TESTER":"3380D","PKG_TYPE":"32_LQFP","Body_Size":"7x7-0.8","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"김희국","socket_no":"32QP-0.8S-SA","pogo_pin":"028S-038AMR-FA","comment":""},
  {"group":"","SN":"4","TESTER":"3380D","PKG_TYPE":"100_LQFP","Body_Size":"14x14-0.5","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"김희국","socket_no":"100QP-0.50S-SA","pogo_pin":"028S-038AMR-FA","comment":""},
  {"group":"","SN":"5","TESTER":"3380D","PKG_TYPE":"120_LQFP","Body_Size":"16x16-0.5","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"김희국","socket_no":"120QP-0.5S-SAR1","pogo_pin":"038S-038MAR-FA","comment":""},
  {"group":"","SN":"6","TESTER":"3380D","PKG_TYPE":"80_LQFP","Body_Size":"12x12-0.5","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"박세영","socket_no":"80QP-0.50S-SA","pogo_pin":"038S-038MAR-FA","comment":""},
  {"group":"","SN":"7","TESTER":"3380D","PKG_TYPE":"64_LQFP","Body_Size":"12x12-0.65","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"이상칠","socket_no":"64QP-0.65S-SA","pogo_pin":"038S-038MAR-FA","comment":""},
  {"group":"","SN":"8","TESTER":"3380D","PKG_TYPE":"100_MQFP","Body_Size":"14x20-0.65","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"이상칠","socket_no":"100QP-0.65S-SA","pogo_pin":"038S-038MAR-FA","comment":""},
  {"group":"","SN":"9","TESTER":"3380D","PKG_TYPE":"64_LQFP ","Body_Size":"14x14-0.8","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"지강찬","socket_no":"64QP-0.80S-SA","pogo_pin":"038S-038MAR-FA","comment":""},
  {"group":"","SN":"10","TESTER":"3380D","PKG_TYPE":"44_LQFP","Body_Size":"10x10-0.8","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"지강찬","socket_no":"44QP-0.80S-SA","pogo_pin":"038S-038MAR-FA","comment":""},
  {"group":"","SN":"11","TESTER":"3380D","PKG_TYPE":"48_QFN","Body_Size":"7x7-0.75T","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"GMTEST","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"1","TESTER":"3380D","PKG_TYPE":"32_LQFP","Body_Size":"7x7-0.8","socket_qty":4,"cover_qty":4,"location":"ABOV","engineer":"FBHS","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"2","TESTER":"3380D","PKG_TYPE":"64_LQFP","Body_Size":"10x10-0.5","socket_qty":4,"cover_qty":4,"location":"ABOV","engineer":"FBHS","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"3","TESTER":"3380D","PKG_TYPE":"44_LQFP","Body_Size":"10x10-0.8","socket_qty":4,"cover_qty":4,"location":"ABOV","engineer":"FBHS","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"4","TESTER":"3380D","PKG_TYPE":"32_QFN","Body_Size":"5x5-0.75T-0.5","socket_qty":8,"cover_qty":8,"location":"ABOV","engineer":"FBHS","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"5","TESTER":"3380D","PKG_TYPE":"80_LQFP","Body_Size":"12x12-0.5","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"FBHS","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"6","TESTER":"3380D","PKG_TYPE":"20_QFN","Body_Size":"4x4-0.75T-0.5","socket_qty":4,"cover_qty":4,"location":"ABOV","engineer":"FBHS","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"7","TESTER":"3380D","PKG_TYPE":"24_QFN","Body_Size":"4x4-0.75T-0.5","socket_qty":4,"cover_qty":4,"location":"ABOV","engineer":"FBHS","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"8","TESTER":"3380D","PKG_TYPE":"","Body_Size":"","socket_qty":0,"cover_qty":0,"location":"","engineer":"","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"1","TESTER":"T3347A","PKG_TYPE":"32_LQFP","Body_Size":"7X7-0.8","socket_qty":2,"cover_qty":4,"location":"ABOV","engineer":"ABOV","socket_no":"CS-LQFP32-7X7-0.8-P1","pogo_pin":"","comment":"7X7 32,48LQFP COK 호환 사용가능"},
  {"group":"","SN":"2","TESTER":"T3347A","PKG_TYPE":"48_LQFP","Body_Size":"7x7-0.5","socket_qty":4,"cover_qty":4,"location":"ABOV","engineer":"ABOV","socket_no":"CS-LQFP48-7X7-0.5-P1","pogo_pin":"","comment":"7X7 32,48LQFP COK 호환 사용가능"},
  {"group":"","SN":"3","TESTER":"T3347A","PKG_TYPE":"64_TQFP","Body_Size":"7X7-0.4","socket_qty":2,"cover_qty":1,"location":"ABOV","engineer":"ABOV","socket_no":"ISC: 64TQFP-0.4P","pogo_pin":"","comment":""},
  {"group":"","SN":"4","TESTER":"T3347A","PKG_TYPE":"44_MQFP","Body_Size":"10X10-0.8","socket_qty":5,"cover_qty":1,"location":"ABOV","engineer":"ABOV","socket_no":"ISC: 44MQFP-0.6P","pogo_pin":"","comment":""},
  {"group":"","SN":"5","TESTER":"T3347A","PKG_TYPE":"44_LQFP","Body_Size":"10X10-0.8","socket_qty":1,"cover_qty":3,"location":"ABOV","engineer":"ABOV","socket_no":"CS-LQFP44-10X10-0.8-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"6","TESTER":"T3347A","PKG_TYPE":"64_LQFP","Body_Size":"10X10-0.5","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"ABOV","socket_no":"CS-LQFP64-10X10-0.5-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"7","TESTER":"T3347A","PKG_TYPE":"80_LQFP","Body_Size":"12X12-0.5","socket_qty":2,"cover_qty":2,"location":"ABOV","engineer":"ABOV","socket_no":"CS-LQFP80-12X12-0.5-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"8","TESTER":"T3347A","PKG_TYPE":"64_LQFP","Body_Size":"12X12-0.65","socket_qty":6,"cover_qty":1,"location":"ABOV","engineer":"ABOV","socket_no":"CS-LQFP64-12X12-0.65-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"9","TESTER":"T3347A","PKG_TYPE":"52_LQFP","Body_Size":"14X14-1.0","socket_qty":4,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"CS-LQFP52-14X14-1.0-P1-N17-630","pogo_pin":"","comment":""},
  {"group":"","SN":"10","TESTER":"T3347A","PKG_TYPE":"64_LQFP","Body_Size":"14X14-0.8","socket_qty":6,"cover_qty":2,"location":"ABOV","engineer":"ABOV","socket_no":"CS-LQFP64-14X14-0.8-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"11","TESTER":"T3347A","PKG_TYPE":"100_LQFP","Body_Size":"14X14","socket_qty":0,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":"* 14X14 64LQFP 호환 사용"},
  {"group":"","SN":"12","TESTER":"T3347A","PKG_TYPE":"80_LQFP","Body_Size":"14X14","socket_qty":0,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":"* 14X14 64LQFP 호환 사용"},
  {"group":"","SN":"13","TESTER":"T3347A","PKG_TYPE":"64_MQFP","Body_Size":"14X20","socket_qty":0,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":"14X20 64,80MQ 호환, 14X20 100MQ는 Blade 교체 필요"},
  {"group":"","SN":"14","TESTER":"T3347A","PKG_TYPE":"80_MQFP","Body_Size":"14X20","socket_qty":0,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"15","TESTER":"T3347A","PKG_TYPE":"100_MQFP","Body_Size":"14X20","socket_qty":0,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"16","TESTER":"T3347A","PKG_TYPE":"20_QFN","Body_Size":"4X4-0.5","socket_qty":8,"cover_qty":1,"location":"ABOV","engineer":"ABOV","socket_no":"CS-QFN20-4X4-0.5-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"17","TESTER":"T3347A","PKG_TYPE":"32_QFN","Body_Size":"5X5-0.5","socket_qty":3,"cover_qty":4,"location":"ABOV","engineer":"ABOV","socket_no":"CS-QFN32-5X5-","pogo_pin":"","comment":""},
  {"group":"","SN":"18","TESTER":"T3347A","PKG_TYPE":"16_QFN","Body_Size":"3X3-0.5","socket_qty":4,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"BC-QFN-3X3-0.5-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"19","TESTER":"T3347A","PKG_TYPE":"48_QFN","Body_Size":"7X7-0.5","socket_qty":0,"cover_qty":1,"location":"ABOV","engineer":"ABOV","socket_no":"BC-QFN-7X7-0.5-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"20","TESTER":"T3347A","PKG_TYPE":"64_QFN","Body_Size":"8X8-0.4","socket_qty":4,"cover_qty":4,"location":"ABOV","engineer":"ABOV","socket_no":"BC-QFN64-8X8-0.4-P1-#004","pogo_pin":"","comment":""},
  {"group":"","SN":"21","TESTER":"T3347A","PKG_TYPE":"24_QFN","Body_Size":"4X4","socket_qty":1,"cover_qty":1,"location":"ABOV","engineer":"ABOV","socket_no":"CS-QFN24-4x4-0.5-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"22","TESTER":"T3347A","PKG_TYPE":"40_QFN","Body_Size":"5X5-0.4","socket_qty":4,"cover_qty":2,"location":"ABOV","engineer":"ABOV","socket_no":"BC-QFN40-5X5-0.4-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"23","TESTER":"T3347A","PKG_TYPE":"68_QFN","Body_Size":"8x8-0.4","socket_qty":5,"cover_qty":5,"location":"ABOV","engineer":"ABOV","socket_no":"BC-68QFN-8X8-0.4-P1-N19-262","pogo_pin":"","comment":""},
  {"group":"","SN":"24","TESTER":"T3347A","PKG_TYPE":"20_QFN","Body_Size":"3x3-0.4","socket_qty":1,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"BC-QFN20-3X3-0.4-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"25","TESTER":"T3347A","PKG_TYPE":"44_QFN","Body_Size":"10X10","socket_qty":0,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"26","TESTER":"T3347A","PKG_TYPE":"28_QFN","Body_Size":"5X5","socket_qty":0,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"27","TESTER":"T3347A","PKG_TYPE":"A31G112KN","Body_Size":"9X9-0.5","socket_qty":0,"cover_qty":1,"location":"ABOV","engineer":"ABOV","socket_no":"BC-QFN64-9X9-0.5-P1","pogo_pin":"","comment":""},
  {"group":"","SN":"28","TESTER":"T3347A","PKG_TYPE":"48_QFN","Body_Size":"6X6-0.5","socket_qty":0,"cover_qty":2,"location":"ABOV","engineer":"ABOV","socket_no":"CSRH-QFN48-6X6-0.5-P1","pogo_pin":"","comment":"Winpac 에서 1set 이동 필요"},
  {"group":"","SN":"29","TESTER":"T3347A","PKG_TYPE":"32_QFN","Body_Size":"5X5-0.5","socket_qty":0,"cover_qty":1,"location":"ABOV","engineer":"ABOV","socket_no":"CS-QFN32-5X5-0.5-P1","pogo_pin":"","comment":"DCT_REV00"},
  {"group":"","SN":"1","TESTER":"3360D","PKG_TYPE":"32_SOP","Body_Size":"300mil","socket_qty":4,"cover_qty":4,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"2","TESTER":"3360D","PKG_TYPE":"28_SOP","Body_Size":"300lin","socket_qty":7,"cover_qty":12,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"3","TESTER":"3360D","PKG_TYPE":"28_TSSOP","Body_Size":"173mil","socket_qty":4,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"4","TESTER":"3360D","PKG_TYPE":"24_SSOP","Body_Size":"209/236(?)","socket_qty":2,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"5","TESTER":"3360D","PKG_TYPE":"28_SSOP","Body_Size":"","socket_qty":2,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"6","TESTER":"3360D","PKG_TYPE":"16_SOP","Body_Size":"150mil","socket_qty":4,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"7","TESTER":"3360D","PKG_TYPE":"10_SSOP-EP","Body_Size":"150mil","socket_qty":3,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"8","TESTER":"3360D","PKG_TYPE":"20_QFN 0.5","Body_Size":"","socket_qty":1,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"9","TESTER":"3360D","PKG_TYPE":"10_DFN","Body_Size":"3x3","socket_qty":1,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"10","TESTER":"3360D","PKG_TYPE":"20_QFN","Body_Size":"4x4x0.75T-0.5","socket_qty":1,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"11","TESTER":"3360D","PKG_TYPE":"20_QFN","Body_Size":"3x3x0.75T-0.4","socket_qty":1,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"12","TESTER":"3360D","PKG_TYPE":"16_QFN","Body_Size":"","socket_qty":3,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"13","TESTER":"3360D","PKG_TYPE":"32_QFN","Body_Size":"","socket_qty":3,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"14","TESTER":"3360D","PKG_TYPE":"16_PIN","Body_Size":"-","socket_qty":0,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":"MANUAL(TOP+BOTTOM)"},
  {"group":"","SN":"15","TESTER":"3360D","PKG_TYPE":"32_PIN","Body_Size":"-","socket_qty":0,"cover_qty":0,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":"MANUAL(TOP+BOTTOM)"},
  {"group":"","SN":"16","TESTER":"3360D","PKG_TYPE":"32_PIN","Body_Size":"-","socket_qty":0,"cover_qty":8,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":"MANUAL(TOP+BOTTOM)"},
  {"group":"","SN":"17","TESTER":"3360D","PKG_TYPE":"REVERSE","Body_Size":"","socket_qty":0,"cover_qty":4,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""},
  {"group":"","SN":"18","TESTER":"3360D","PKG_TYPE":"20_QFN","Body_Size":"","socket_qty":4,"cover_qty":4,"location":"ABOV","engineer":"ABOV","socket_no":"","pogo_pin":"","comment":""}
];
